In [13]:
import numpy as np

In [14]:
a = np.array([[6,4,24],[1,-9,8]])
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [15]:
type(a)

numpy.ndarray

In [16]:
a.shape

(2, 3)

In [17]:
a.size

6

In [18]:
a[0]

array([ 6,  4, 24])

In [19]:
a[1]

array([ 1, -9,  8])

In [20]:
a[:,0]

array([6, 1])

In [21]:
a[:,1]

array([ 4, -9])

In [22]:
a[:,2]

array([24,  8])

In [23]:
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [24]:
a[0][1]

np.int64(4)

In [25]:
a[0][0]

np.int64(6)

In [26]:
a[:1]

array([[ 6,  4, 24]])

In [27]:
a[:0]

array([], shape=(0, 3), dtype=int64)

In [28]:
a = np.array([[6,4,24],[1,-9,8],[1,2,3]])
print(a)


[[ 6  4 24]
 [ 1 -9  8]
 [ 1  2  3]]


In [29]:
a[1:3]

array([[ 1, -9,  8],
       [ 1,  2,  3]])

In [30]:
a[0:2]

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [31]:
a[0:2 , :2]

array([[ 6,  4],
       [ 1, -9]])

In [32]:
a.sum()

np.int64(40)

In [33]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [34]:
b.sum()

np.int64(10)

In [35]:
b.sum(axis=0)

array([4, 6])

In [36]:
b.sum(axis=1)

array([3, 7])

In [37]:
c = b * 2

In [38]:
print(c)

[[2 4]
 [6 8]]


In [39]:
d = np.array([[4,5],[2,0]])
e = np.array([[4,6],[7,1]])

In [40]:
print(d)
print(e)

[[4 5]
 [2 0]]
[[4 6]
 [7 1]]


In [41]:
d + e

array([[ 8, 11],
       [ 9,  1]])

In [42]:
d - e

array([[ 0, -1],
       [-5, -1]])

In [43]:
d * e

array([[16, 30],
       [14,  0]])

In [44]:
np.dot(d,e)

array([[51, 29],
       [ 8, 12]])

In [45]:
f = np.array([[1,2,3],[4,5,6]])
g = np.array([[10,11],[20,21],[30,31]])

In [46]:
print(f)

[[1 2 3]
 [4 5 6]]


In [47]:
print(g)

[[10 11]
 [20 21]
 [30 31]]


In [48]:
f.shape

(2, 3)

In [49]:
g.shape

(3, 2)

In [50]:
h = np.dot(f,g)

In [51]:
print(h)

[[140 146]
 [320 335]]



In [52]:
i = np.dot(g,f)
print(i)

[[ 54  75  96]
 [104 145 186]
 [154 215 276]]


In [53]:
j = np.array([[1,2,3],[4,5,6]])
j.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
j.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
k = np.array([[0,1,2],[1,7,8], [2,8,9]])
print(k)

[[0 1 2]
 [1 7 8]
 [2 8 9]]


In [56]:
k.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [57]:
l = k.T

In [58]:
print(l)

[[0 1 2]
 [1 7 8]
 [2 8 9]]


In [59]:
l == k

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [60]:
m = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
np.trace(m)

np.int64(15)

In [62]:
n = m.T

In [63]:
np.trace(n)

np.int64(15)

In [64]:
x = np.array([[8,3],[4,2]])
print(x)

[[8 3]
 [4 2]]


In [65]:
np.linalg.det(x)

np.float64(3.999999999999999)

In [66]:
y = np.array([[1,2,3],[3,1,2],[0,0,1]])
print(y)

[[1 2 3]
 [3 1 2]
 [0 0 1]]


In [67]:
np.linalg.det(y)

np.float64(-5.000000000000001)

In [68]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
np.linalg.det(z)

np.float64(0.0)

In [70]:
a = np.array([[4,3],[3,2]])
print(a)

[[4 3]
 [3 2]]


In [71]:
np.linalg.inv(a)

array([[-2.,  3.],
       [ 3., -4.]])

In [72]:
b = np.array([[1,2,3],[0,1,4],[5,6,0]])
print(b)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [73]:
np.linalg.inv(b)

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [74]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [75]:
np.linalg.norm(a)

np.float64(5.477225575051661)

In [76]:
np.sqrt(np.trace(a.dot(a.T)))

np.float64(5.477225575051661)

In [77]:
import sympy as sp

In [89]:
a = sp.Matrix([[3,4],[2,3]])
a

Matrix([
[3, 4],
[2, 3]])

In [90]:
a.row(0)

Matrix([[3, 4]])

In [91]:
a.col(0)

Matrix([
[3],
[2]])

In [92]:
a.shape

(2, 2)

In [93]:
a.inv()

Matrix([
[ 3, -4],
[-2,  3]])

In [94]:
a.det()

1

In [84]:
sp.zeros(4,5)

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [85]:
sp.eye(5)

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

In [86]:
sp.diag(1,2,3,4)

Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0],
[0, 0, 0, 4]])