# 📐 Matrix Operations, Properties, and Inverses

**Course**: Machine Learning Mathematics — Lecture Notes
**Topic**: Matrix Algebra, Determinants, Inverses, Trace, and Matrix Norms

## 1. Matrix Representation and Indexing

### Intuition First
In machine learning, datasets are formatted as 2D tabular matrices $A \in \mathbb{R}^{m \times n}$, where each of the $m$ rows represents a single sample (observation), and each of the $n$ columns represents a distinct feature variable. Matrices also represent linear transformations that warp, rotate, or scale space.

### Formal Definition / Math
A matrix $A \in \mathbb{R}^{m \times n}$ is defined as a rectangular array of scalars:

$$\begin{equation}
A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{bmatrix}
\end{equation}$$

where:
- $m$: Number of rows.
- $n$: Number of columns.
- $a_{ij}$: Entry located at row index $i$ ($1 \le i \le m$) and column index $j$ ($1 \le j \le n$).

### Connection to the Code
- `rect_matrix = np.array([[6,4,24],[1,-9,8]])` creates $A \in \mathbb{R}^{2 \times 3}$.
- `rect_matrix.shape` returns $(2, 3)$.
- `rect_matrix.size` returns total elements $2 \times 3 = 6$.

**Key Takeaway**: **A matrix $A \in \mathbb{R}^{m \times n}$ represents an $m \times n$ grid of numerical data points and feature attributes.**

In [ ]:
import numpy as np
import sys

sys.path.append("..")

In [2]:
rect_matrix = np.array([[6, 4, 24], [1, -9, 8]])
print("Matrix:")
print(rect_matrix)
print(f"Shape: {rect_matrix.shape}")
print(f"Size: {rect_matrix.size}")
print(f"Element (0,1): {rect_matrix[0, 1]}")
print(f"Row 0: {rect_matrix[0, :]}")
print(f"Column 2: {rect_matrix[:, 2]}")

Matrix:
[[ 6  4 24]
 [ 1 -9  8]]
Shape: (2, 3)
Size: 6
Element (0,1): 4
Row 0: [ 6  4 24]
Column 2: [24  8]


## 2. Matrix Arithmetic & Transposition

### Intuition First
Addition and scalar multiplication act component-wise on matrices of identical shape. Transposition flips a matrix across its main diagonal, swapping rows for columns—converting an $m \times n$ matrix into an $n \times m$ matrix.

### Formal Definition / Math
- **Addition**: $(A + B)_{ij} = a_{ij} + b_{ij}$ for $A, B \in \mathbb{R}^{m \times n}$.
- **Transposition**: For $A \in \mathbb{R}^{m \times n}$, $A^T \in \mathbb{R}^{n \times m}$ where $(A^T)_{ij} = a_{ji}$.

### Connection to the Code
- `rect_matrix.T` or `np.transpose(rect_matrix)` computes matrix transpose $A^T$.

### Worked Micro-Example
For $A = \begin{bmatrix} 6 & 4 & 24 \\ 1 & -9 & 8 \end{bmatrix} \in \mathbb{R}^{2 \times 3}$, $A^T = \begin{bmatrix} 6 & 1 \\ 4 & -9 \\ 24 & 8 \end{bmatrix} \in \mathbb{R}^{3 \times 2}$.

**Key Takeaway**: **Transposition swaps rows and columns, transforming $A \in \mathbb{R}^{m \times n}$ into $A^T \in \mathbb{R}^{n \times m}$.**

In [3]:
transposed_matrix = rect_matrix.T
print("Original Matrix (2x3):")
print(rect_matrix)
print("Transposed Matrix (3x2):")
print(transposed_matrix)

Original Matrix (2x3):
[[ 6  4 24]
 [ 1 -9  8]]
Transposed Matrix (3x2):
[[ 6  1]
 [ 4 -9]
 [24  8]]


## 3. Matrix Multiplication (Dot Product)

### Intuition First
Matrix multiplication represents the composition of sequential linear transformations. Unlike scalar arithmetic, matrix multiplication is generally **non-commutative** ($A B \neq B A$).

### Formal Definition / Math
The matrix product $C = A B$ of $A \in \mathbb{R}^{m \times k}$ and $B \in \mathbb{R}^{k \times n}$ is defined as $C \in \mathbb{R}^{m \times n}$ with entries:

$$\begin{equation}
c_{ij} = \sum_{p=1}^k a_{ip} b_{pj}
\end{equation}$$

Inner dimensions **must match**: $(m \times k) \cdot (k \times n) \to (m \times n)$.

### Connection to the Code
- `np.dot(A, B)` or `A @ B` performs valid matrix multiplication $C = AB$.

### Common Pitfalls / Notes
Using `A * B` performs element-wise Hadamard product, not standard matrix multiplication. Always use `@` or `np.dot` for linear algebra matrix multiplication.

**Key Takeaway**: **Matrix multiplication requires inner dimension compatibility $(m \times k) \times (k \times n)$ and computes row-column dot products.**

In [4]:
A = rect_matrix
B = rect_matrix.T
C = np.dot(A, B)

print("Matrix A (2x3):")
print(A)
print("\nMatrix B (3x2):")
print(B)
print("\nProduct C = A @ B (2x2):")
print(C)

Matrix A (2x3):
[[ 6  4 24]
 [ 1 -9  8]]

Matrix B (3x2):
[[ 6  1]
 [ 4 -9]
 [24  8]]

Product C = A @ B (2x2):
[[628  164]
 [162  146]]


## 4. Determinants, Inverses, and Trace

### Intuition First
The **determinant** $\det(A)$ measures how a matrix scales area or volume in space; if $\det(A) = 0$, the matrix collapses space onto lower dimensions and cannot be inverted. The **inverse** $A^{-1}$ undoes the linear transformation $A$. The **trace** $\text{Tr}(A)$ sums the main diagonal entries.

### Formal Definition / Math
- **Determinant (2x2)**: For $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$, $\det(A) = ad - bc$.
- **Inverse**: $A A^{-1} = A^{-1} A = I_n$. Exists if and only if $\det(A) \neq 0$.
- **Trace**: $\text{Tr}(A) = \sum_{i=1}^n a_{ii}$.

### Connection to the Code
- `np.linalg.det(C)` computes determinant $\det(C)$.
- `np.linalg.inv(C)` computes matrix inverse $C^{-1}$.
- `np.trace(C)` computes trace $\text{Tr}(C)$.

**Key Takeaway**: **A square matrix is invertible if and only if $\det(A) \neq 0$, satisfying $A A^{-1} = I$.**

In [5]:
det_C = np.linalg.det(C)
trace_C = np.trace(C)
inv_C = np.linalg.inv(C)
identity_check = np.dot(C, inv_C)

print("Matrix C (2x2):")
print(C)
print(f"Determinant det(C): {det_C:.4f}")
print(f"Trace Tr(C): {trace_C}")
print("Inverse C^(-1):")
print(inv_C)
print("Identity Verification C @ C^(-1):")
print(np.round(identity_check, 4))

Matrix C (2x2):
[[628 164]
 [162 146]]
Determinant det(C): 65120.0000
Trace Tr(C): 774
Inverse C^(-1):
[[ 0.00224202 -0.00251843]
 [-0.00248771  0.00964373]]
Identity Verification C @ C^(-1):
[[1. 0.]
 [0. 1.]]
