In [1]:
import numpy as np

In [ ]:
A = np.array([[1, 4], [3, 2]])
print(A)

[[1 4]
 [3 2]]


In [ ]:
L, V = np.linalg.eig(A)

In [11]:
print(L)

[-2.+0.j  5.+0.j]


In [10]:
print(np.around(V, decimals=1))

[[-0.8+0.j -0.7+0.j]
 [ 0.6+0.j -0.7+0.j]]


In [13]:
print(L[0])

(-2+0j)


In [14]:
print(L[1])

(5+0j)


In [15]:
# AV = l * v

In [ ]:
-2 * V[:, 0]

array([ 1.6-0.j, -1.2+0.j])

In [18]:
A

array([[1, 4],
       [3, 2]])

In [ ]:
np.dot(A, V[:, 0])

array([ 1.6+0.j, -1.2+0.j])

In [ ]:
5 * V[:, 1]

array([-3.53553391+0.j, -3.53553391+0.j])

In [ ]:
np.dot(A, V[:, 1])

array([-3.53553391+0.j, -3.53553391+0.j])

In [ ]:
A = np.array([[1, 2, 3], [0, 3, 0], [0, 0, 1]])
print(A)

[[1 2 3]
 [0 3 0]
 [0 0 1]]


In [25]:
L, V = np.linalg.eig(A)

In [27]:
print(L)

[1.+0.j 3.+0.j 1.+0.j]


In [29]:
print(np.around(V, decimals=1))

[[ 1. +0.j  0.7+0.j -1. +0.j]
 [ 0. +0.j  0.7+0.j  0. +0.j]
 [ 0. +0.j  0. +0.j  0. +0.j]]


In [30]:
import sympy as sp

In [ ]:
A = sp.Matrix([[1, 2, 3], [0, 3, 0], [0, 0, 1]])
A

Matrix([
[1, 2, 3],
[0, 3, 0],
[0, 0, 1]])

In [35]:
A.eigenvals()

{3: 1, 1: 2}

In [36]:
A.eigenvects()

[(1,
  2,
  [Matrix([
   [1],
   [0],
   [0]])]),
 (3,
  1,
  [Matrix([
   [1],
   [1],
   [0]])])]