# 📐 Eigenvalues and Eigenvectors

**Course**: Machine Learning Mathematics — Lecture Notes
**Topic**: Spectral Theory, Characteristic Equations & Eigendecomposition

## 1. Introduction to Eigenvalues & Eigenvectors

### Intuition First
When a square matrix $A$ acts on a generic vector $x$, it typically scales the vector's length and rotates its direction in space. However, for certain special non-zero vectors $v$, matrix $A$ acts as a simple scalar multiplier: it stretches or shrinks vector $v$ along its own direction without rotating it at all. These invariant directions $v$ are called **eigenvectors**, and the corresponding scaling factors $\lambda$ are called **eigenvalues**.

### Formal Definition / Math
For a square matrix $A \in \mathbb{R}^{n \times n}$, a scalar $\lambda \in \mathbb{C}$ and a non-zero vector $v \in \mathbb{C}^n \setminus \{0\}$ are called an **eigenvalue** and **eigenvector** pair of $A$ if they satisfy the eigenvalue equation:

$$\begin{equation}
A v = \lambda v
\end{equation}$$

To solve for $\lambda$, rewrite equation (1) as $(A - \lambda I)v = 0$. For a non-trivial solution $v \neq 0$ to exist, the coefficient matrix $(A - \lambda I)$ must be singular (non-invertible), which requires its determinant to be zero:

$$\begin{equation}
p(\lambda) = \det(A - \lambda I) = 0
\end{equation}$$

where $p(\lambda)$ is the $n$-th degree polynomial known as the **characteristic polynomial** of $A$.

### Connection to the Code
Below, we import `numpy` to compute numerical eigenvalues and eigenvectors using `np.linalg.eig`.

**Key Takeaway**: **Eigenvectors represent invariant direction vectors for a linear transformation $A$, satisfying $Av = \lambda v$.**

In [1]:
import numpy as np

## 2. Numerical Eigendecomposition with NumPy

### Intuition First
We test eigendecomposition on a 2x2 matrix $A = \begin{bmatrix} 1 & 4 \\ 3 & 2 \end{bmatrix}$ to see how `np.linalg.eig` computes eigenvalues and unit-normalized eigenvectors.

### Formal Definition / Math
The characteristic equation for $A = \begin{bmatrix} 1 & 4 \\ 3 & 2 \end{bmatrix}$ is:

$$\det \begin{bmatrix} 1 - \lambda & 4 \\ 3 & 2 - \lambda \end{bmatrix} = (1-\lambda)(2-\lambda) - 12 = \lambda^2 - 3\lambda - 10 = 0$$

Factoring yields $(\lambda - 5)(\lambda + 2) = 0$, giving eigenvalues $\lambda_1 = -2$ and $\lambda_2 = 5$.

### Connection to the Code
- Matrix $A$ is created with `np.array([[1, 4], [3, 2]])`.
- `L, V = np.linalg.eig(A)` computes eigenvalues `L` and normalized column eigenvectors `V`.
- `V[:, 0]` is the eigenvector corresponding to `L[0]` ($\lambda_1 = -2$).
- `V[:, 1]` is the eigenvector corresponding to `L[1]` ($\lambda_2 = 5$).

### Common Pitfalls / Notes
Eigenvectors returned by `np.linalg.eig` are normalized to unit $\ell_2$-norm ($\|v\|_2 = 1$) and stored as **columns** in array `V`, not rows.

In [2]:
A = np.array([[1, 4], [3, 2]])
print(A)

[[1 4]
 [3 2]]


In [3]:
L, V = np.linalg.eig(A)

In [4]:
print(L)

[-2.+0.j  5.+0.j]


In [5]:
print(np.around(V, decimals=1))

[[-0.8+0.j -0.7+0.j]
 [ 0.6+0.j -0.7+0.j]]


In [6]:
print(L[0])

(-2+0j)


In [7]:
print(L[1])

(5+0j)


## 3. Verifying $A v = \lambda v$ Identity

### Intuition First
We directly verify that matrix-vector multiplication $A v$ produces the exact same result vector as scalar-vector multiplication $\lambda v$.

### Connection to the Code
- `-2 * V[:, 0]` computes scalar product $\lambda_1 v_1$.
- `np.dot(A, V[:, 0])` computes matrix multiplication $A v_1$.
- `5 * V[:, 1]` computes scalar product $\lambda_2 v_2$.
- `np.dot(A, V[:, 1])` computes matrix multiplication $A v_2$.

**Key Takeaway**: **Both computational methods yield identical results, confirming that $Av = \lambda v$ holds exactly.**

In [8]:
-2 * V[:, 0]

array([ 1.6-0.j, -1.2+0.j])

In [9]:
A

array([[1, 4],
       [3, 2]])

In [10]:
np.dot(A, V[:, 0])

array([ 1.6+0.j, -1.2+0.j])

In [11]:
5 * V[:, 1]

array([-3.53553391+0.j, -3.53553391+0.j])

In [12]:
np.dot(A, V[:, 1])

array([-3.53553391+0.j, -3.53553391+0.j])

## 4. Symbolic Eigendecomposition with SymPy

### Intuition First
While NumPy calculates floating-point approximations, SymPy allows us to compute exact algebraic eigenvalues, multiplicities, and exact eigenspace basis vectors.

### Formal Definition / Math
For upper-triangular matrix $A = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 3 & 0 \\ 0 & 0 & 1 \end{bmatrix}$, the diagonal entries are the eigenvalues: $\lambda_1 = 1$ (multiplicity 2) and $\lambda_2 = 3$ (multiplicity 1).

### Connection to the Code
- `A.eigenvals()` returns dictionary `{eigenvalue: algebraic_multiplicity}`.
- `A.eigenvects()` returns list of tuples `[(eigenvalue, multiplicity, [basis_vectors])]`.

**Key Takeaway**: **SymPy provides exact analytical solutions for eigenvalues and eigenspace bases without numerical round-off error.**

In [13]:
A = np.array([[1, 2, 3], [0, 3, 0], [0, 0, 1]])
print(A)

[[1 2 3]
 [0 3 0]
 [0 0 1]]


In [14]:
L, V = np.linalg.eig(A)

In [15]:
print(L)

[1.+0.j 3.+0.j 1.+0.j]


In [16]:
print(np.around(V, decimals=1))

[[ 1. +0.j  0.7+0.j -1. +0.j]
 [ 0. +0.j  0.7+0.j  0. +0.j]
 [ 0. +0.j  0. +0.j  0. +0.j]]


In [17]:
import sympy as sp

In [18]:
A_sp = sp.Matrix([[1, 2, 3], [0, 3, 0], [0, 0, 1]])
A_sp

Matrix([
[1, 2, 3],
[0, 3, 0],
[0, 0, 1]])

In [19]:
A_sp.eigenvals()

{3: 1, 1: 2}

In [20]:
A_sp.eigenvects()

[(1,
  2,
  [Matrix([
   [1],
   [0],
   [0]])]),
 (3,
  1,
  [Matrix([
   [1],
   [0],
   [0]])])]