# 📐 Singular Value Decomposition (SVD)

**Course**: Machine Learning Mathematics — Lecture Notes
**Topic**: Matrix Decompositions & Dimensionality Reduction

## 1. The Fundamental Theorem of SVD

### Intuition First
Eigenvalue decomposition works wonders for square matrices, but real-world machine learning datasets are almost never square. Data matrices $A \in \mathbb{R}^{m \times n}$ usually represent $m$ samples with $n$ features. Singular Value Decomposition (SVD) generalizes matrix factorization to **any** rectangular real or complex matrix. Geometrically, SVD decomposes any linear transformation into three sequential fundamental actions: a rotation in the domain, a scaling along coordinate axes, and a rotation in the target codomain.

### Formal Definition / Math
For any matrix $A \in \mathbb{R}^{m \times n}$, its Singular Value Decomposition is defined as:

$$\begin{equation}
A = U \Sigma V^T
\end{equation}$$

where:
- $A \in \mathbb{R}^{m \times n}$: The original input matrix of rank $r \le \min(m, n)$.
- $U \in \mathbb{R}^{m \times m}$: An orthogonal matrix containing the **left-singular vectors** $u_i$ as columns. These are eigenvectors of $A A^T$.
- $\Sigma \in \mathbb{R}^{m \times n}$: A diagonal matrix containing non-negative **singular values** $\sigma_1 \ge \sigma_2 \ge \dots \ge \sigma_r > 0$ ordered in descending magnitude.
- $V^T \in \mathbb{R}^{n \times n}$: The transpose of an orthogonal matrix $V$ containing the **right-singular vectors** $v_i$ as columns. These are eigenvectors of $A^T A$.

#### Derivation Steps:
1. Form the symmetric matrix $A^T A \in \mathbb{R}^{n \times n}$. Compute its eigenvalues $\lambda_i$ and orthonormal eigenvectors $v_i$ such that $(A^T A) v_i = \lambda_i v_i$.
2. The singular values are defined as $\sigma_i = \sqrt{\lambda_i}$ for $\lambda_i \ge 0$.
3. The left singular vectors are computed as $u_i = \frac{1}{\sigma_i} A v_i$.

### Connection to the Code
In the cell below, we import `numpy` and initialize matrix $A \in \mathbb{R}^{2 \times 3}$, corresponding to $m=2$ rows and $n=3$ columns.

### Worked Micro-Example
Given $A = \begin{bmatrix} 3 & 1 & 1 \\ -1 & 3 & 1 \end{bmatrix}$:
- $A A^T = \begin{bmatrix} 11 & 1 \\ 1 & 11 \end{bmatrix}$, yielding eigenvalues $\lambda_1 = 12, \lambda_2 = 10$.
- Singular values are $\sigma_1 = \sqrt{12} = 2\sqrt{3} \approx 3.464$ and $\sigma_2 = \sqrt{10} \approx 3.162$.

### Common Pitfalls / Notes
NumPy's `np.linalg.svd` returns $V^T$ directly (not $V$), so matrix multiplication must use `np.dot(U, np.dot(Sigma, Vt))` directly without re-transposing $V^T$.

**Key Takeaway**: **SVD factorizes any matrix $A$ into orthogonal rotations $U, V^T$ and non-negative diagonal scaling factors $\Sigma$, forming the foundation for Principal Component Analysis (PCA) and low-rank matrix approximations.**

In [ ]:
import numpy as np
import sys

sys.path.append("..")
from src.utils import compute_svd_reconstruction

## 2. Defining the Target Matrix

### Intuition First
We select a concrete rectangular matrix $A \in \mathbb{R}^{2 \times 3}$ to numerically compute its singular value components.

### Connection to the Code
Variable `A` in the code block represents the matrix $A = \begin{bmatrix} 3 & 1 & 1 \\ -1 & 3 & 1 \end{bmatrix}$.

In [2]:
A = np.array([[3, 1, 1], [-1, 3, 1]], dtype=float)
print("Matrix A (shape 2x3):")
print(A)

Matrix A (shape 2x3):
[[ 3  1  1]
 [-1  3  1]]


## 3. Computing SVD Numerically & Matrix Reconstruction

### Intuition First
To verify that SVD correctly decomposes $A$, we compute the components $U, \Sigma, V^T$ using NumPy's numerical linear algebra suite and verify that multiplying them back together reconstructs the exact original matrix $A$.

### Formal Definition / Math
The full SVD matrix form requires forming $\Sigma \in \mathbb{R}^{m \times n}$ as a padded zero matrix:

$$\begin{equation}
\Sigma = \begin{bmatrix} \sigma_1 & 0 & 0 \\ 0 & \sigma_2 & 0 \end{bmatrix}
\end{equation}$$

Matrix reconstruction follows exact matrix multiplication:

$$\begin{equation}
A = U \cdot \Sigma \cdot V^T
\end{equation}$$

### Connection to the Code
- `U, S, Vt = np.linalg.svd(A)` returns left singular matrix `U`, 1D array of singular values `S`, and transposed right singular matrix `Vt`.
- `compute_svd_reconstruction(A, k=2)` calls our reusable module in `src/utils.py` to reconstruct $A$.

**Key Takeaway**: **Numerical SVD accurately reconstructs the input matrix, confirming that $U \Sigma V^T = A$ holds to floating-point precision.**

In [3]:
# Perform SVD computation using NumPy
U, S, Vt = np.linalg.svd(A)

# Utilize extracted module solver for verification
U_k, S_k, Vt_k, A_reconstructed = compute_svd_reconstruction(A, k=2)

print("Singular Values S:", S)
print("\nReconstructed Matrix A_reconstructed:")
print(np.round(A_reconstructed, 4))
print(f"\nReconstruction Error Norm: {np.linalg.norm(A - A_reconstructed):e}")

Singular Values S: [3.46410162 3.16227766]

Reconstructed Matrix A_reconstructed:
[[ 3.  1.  1.]
 [-1.  3.  1.]]

Reconstruction Error Norm: 0.000000e+00
